# question_bank.py

# 100% Accurate & Relevant High School Textbook Curriculum Database
ACADEMIC_DATABASE = {
    "Physics": {
        "Electric Charges and Fields": {
            "definition": "Electric Charge is a fundamental physical property of matter that causes it to experience a force when placed in an electromagnetic field. Electric Fields represent the region space around a charged particle where its force can be exerted on other charges.",
            "explanation": "Charges are quantized ($q = ne$) and conserved, existing as positive (protons) or negative (electrons). Coulomb's Law quantifies the electrostatic force between two point charges, stating it is directly proportional to the product of the charges and inversely proportional to the square of the distance between them. Electric field intensity ($E$) is measured as force per unit charge.",
            "keywords": ["Coulombs Law", "Quantization", "Permittivity", "Electrostatic Force", "Field Lines"]
        },
        "Electrostatic Potential and Capacitance": {
            "definition": "Electrostatic Potential is the amount of work done in bringing a unit positive charge from infinity to a specific point in an electric field. Capacitance is the ability of a system to store electric charge per unit potential difference.",
            "explanation": "Potential is a scalar quantity indicating electrical state. A Capacitor typically consists of two conducting plates separated by an insulator (dielectric). Introducing a dielectric material between the plates decreases the electric field, thereby increasing the overall capacitance ($C = Q/V$).",
            "keywords": ["Potential Difference", "Dielectric Constant", "Equipotential Surface", "Capacitor Plates", "Stored Energy"]
        },
        "Current Electricity": {
            "definition": "Current Electricity is the study of electric charges in motion, where electric current ($I$) is defined as the time rate of flow of net charge across a cross-section.",
            "explanation": "Ohm's Law states that current is directly proportional to potential difference across a conductor, provided temperature remains constant ($V = IR$). Factors like drift velocity of electrons, resistivity of material structures, and temperature coefficients dictate electrical resistance. Kirchhoff's Laws govern complex circuit analysis using charge and energy conservation.",
            "keywords": ["Ohms Law", "Drift Velocity", "Resistivity", "Kirchhoffs Circuit Laws", "Potentiometer"]
        },
        "Moving Charges and Magnetism": {
            "definition": "This field examines how moving electric charges create magnetic fields and how external magnetic fields exert forces on moving charges and currents.",
            "explanation": "Biot-Savart Law and Ampere's Circuital Law are used to calculate magnetic fields generated by current-carrying conductors. The Lorentz Force formula calculates the total force on a charge moving through simultaneous electric and magnetic fields. Cyclotrons and galvanometers apply these principles.",
            "keywords": ["Biot Savart Law", "Amperes Law", "Lorentz Force", "Magnetic Dipole", "Galvanometer"]
        },
        "Magnetism and Matter": {
            "definition": "This topic explores the magnetic properties of materials and the Earth's natural magnetic field parameters.",
            "explanation": "Materials are classified based on magnetic behavior into Diamagnetic (repelled by fields), Paramagnetic (weakly attracted), and Ferromagnetic (strongly attracted). Earth's magnetism is defined by elements like magnetic declination, inclination (dip), and the horizontal component of the earth's field.",
            "keywords": ["Ferromagnetism", "Magnetic Declination", "Magnetic Dip", "Susceptibility", "Retentivity"]
        },
        "Electromagnetic Induction": {
            "definition": "Electromagnetic Induction is the phenomenon of generating an electromotive force (emf) or current in a conductor by varying the magnetic flux linked with it.",
            "explanation": "Faraday's Laws state that induced emf magnitude equals the time rate of change of magnetic flux. Lenz's Law establishes that the direction of induced current opposes the change in magnetic flux that created it. Self-induction and mutual induction form the basis for electrical inductors.",
            "keywords": ["Faradays Law", "Lenzs Law", "Magnetic Flux", "Eddy Currents", "Mutual Induction"]
        },
        "Alternating Current": {
            "definition": "Alternating Current (AC) is an electric current that periodically reverses direction and changes its magnitude continuously with time.",
            "explanation": "AC circuits involve root-mean-square (RMS) values of voltage and current. When AC flows through resistors, inductors, or capacitors, it encounters impedance. In series LCR circuits, resonance occurs when inductive reactance equals capacitive reactance, maximizing current flow.",
            "keywords": ["Impedance", "LCR Circuit", "Resonance", "Power Factor", "Transformer Step"]
        },
        "Electromagnetic Waves": {
            "definition": "Electromagnetic Waves are coupled, time-varying electric and magnetic fields propagating through space at the speed of light, generated by accelerating charges.",
            "explanation": "Maxwell's equations unified electricity and magnetism, introducing displacement current. The electromagnetic spectrum categorizes these waves by frequency, ranging from low-frequency radio waves to high-energy gamma rays, all traveling transverse to propagation direction.",
            "keywords": ["Displacement Current", "Maxwell Equations", "Transverse Nature", "Spectrum Frequency", "Radiation Pressure"]
        },
        "Ray Optics and Optical Instruments": {
            "definition": "Ray Optics treats light as straight-line rays to study phenomena like reflection, refraction, and image formation by mirrors and lenses.",
            "explanation": "Key principles include Snell's Law of refraction, Total Internal Reflection (TIR), and the lens maker's formula. Optical instruments like microscopes and astronomical telescopes use combinations of lenses to magnify distant or minute specimens.",
            "keywords": ["Snells Law", "Total Internal Reflection", "Lens Makers Formula", "Refractive Index", "Magnification"]
        },
        "Wave Optics": {
            "definition": "Wave Optics considers light as a wavefront to explain phenomena that ray optics cannot model, such as interference, diffraction, and polarization.",
            "explanation": "Huygens' Principle explains wavefront propagation. Huygens' ideas model how light waves superimpose to create bright and dark fringes in Young's Double Slit Experiment (Interference). Diffraction describes light bending around obstacles, while polarization proves light's transverse nature.",
            "keywords": ["Huygens Principle", "Interference Fringes", "Coherent Sources", "Diffraction Grating", "Polarization"]
        },
        "Dual Nature of Radiation and Matter": {
            "definition": "This topic establishes that both radiation (light) and matter exhibit particle-like as well as wave-like properties depending on the experiment.",
            "explanation": "The Photoelectric Effect proves light behaves as discrete packets of energy called photons, where electron emission depends on threshold frequency. Conversely, de Broglie hypothesized that moving matter particles possess a wavelength ($\lambda = h/p$), confirming matter waves.",
            "keywords": ["Photoelectric Effect", "Work Function", "Threshold Frequency", "Photons", "De Broglie Wavelength"]
        },
        "Atoms": {
            "definition": "This chapter details the internal structure of atoms, modeling the arrangement of subatomic particles.",
            "explanation": "Alpha-particle scattering experiments led to Rutherford's nuclear model. Bohr's model improved this by introducing quantized electron orbits, explaining hydrogen spectral line series (Lyman, Balmer, Paschen) through energy level transitions.",
            "keywords": ["Bohr Model", "Quantized Orbits", "Rutherford Scattering", "Energy Levels", "Hydrogen Spectrum"]
        },
        "Nuclei": {
            "definition": "Nuclei focuses on the core center of the atom, examining protons, neutrons, nuclear forces, and nuclear reactions.",
            "explanation": "The nucleus is held together by the strong nuclear force, overcoming electrostatic repulsion. Mass defect explains that missing mass converts into nuclear binding energy ($E=mc^2$). Nuclear Fission splits heavy nuclei, while Nuclear Fusion combines light nuclei, releasing immense energy.",
            "keywords": ["Mass Defect", "Binding Energy", "Nuclear Fission", "Nuclear Fusion", "Strong Force"]
        },
        "Semiconductor Electronics": {
            "definition": "Semiconductor Electronics studies devices whose electrical conductivity lies between conductors and insulators, controlled by doping impurities.",
            "explanation": "Intrinsic semiconductors are pure crystals, while extrinsic semiconductors are doped (n-type with pentavalent, p-type with trivalent impurities). P-N Junction diodes permit current in forward bias and block it in reverse bias, working as rectifiers or logic gates.",
            "keywords": ["PN Junction", "Doping Impurities", "Forward Bias", "Rectification", "Logic Gates"]
        }
    },
    "Chemistry": {
        "Solutions": {
            "definition": "A Solution is a homogeneous mixture of two or more chemically non-reacting substances whose composition can be varied within certain limits.",
            "explanation": "Liquid solutions depend on vapor pressure dynamics. Henry's Law governs gas solubility in liquids. Raoult's Law states that the partial vapor pressure of a volatile component is proportional to its mole fraction. Colligative properties depend solely on solute particle count, including boiling point elevation and osmotic pressure.",
            "keywords": ["Raoults Law", "Molarity", "Colligative Properties", "Osmotic Pressure", "Vant Hoff Factor"]
        },
        "Electrochemistry": {
            "definition": "Electrochemistry is the study of chemical reactions that produce electricity and the use of electricity to drive non-spontaneous chemical transformations.",
            "explanation": "Electrochemical cells convert chemical energy to electrical energy, modeled by the Nernst Equation to calculate cell potential. Electrolytic cells utilize external current for decomposition. Kohlrausch's Law helps determine the limiting molar conductivity of weak electrolytes.",
            "keywords": ["Nernst Equation", "Galvanic Cell", "Anode Cathode", "Electrolysis", "Kohlrausch Law"]
        },
        "Chemical Kinetics": {
            "definition": "Chemical Kinetics is the branch of chemistry concerned with the rates of chemical reactions, factors affecting them, and the underlying reaction mechanism.",
            "explanation": "Reaction rates depend on reactant concentration, temperature, and catalysts. Rate laws express velocity in terms of rate constants and reaction order (zero, first, or second order). Collision theory and the Arrhenius equation model how activation energy dictates reaction speed.",
            "keywords": ["Reaction Rate", "Activation Energy", "Arrhenius Equation", "First Order Reaction", "Catalyst Acceleration"]
        },
        "Surface Chemistry": {
            "definition": "Surface Chemistry deals with chemical and physical phenomena occurring at the interface or surface of phases.",
            "explanation": "Adsorption is a surface phenomenon where substance concentration increases at the boundary (divided into physical physisorption and chemical chemisorption). Colloids represent a state where particle sizes fall between true solutions and suspensions, showing the Tyndall effect.",
            "keywords": ["Adsorption Isotherm", "Physisorption", "Chemisorption", "Colloidal State", "Tyndall Effect"]
        },
        "General Principles and Processes of Isolation of Elements": {
            "definition": "This chapter details the metallurgical extraction processes used to isolate pure metals from their naturally occurring ores.",
            "explanation": "Metallurgy involves concentration of ore (froth floatation, leaching), conversion to oxide (calcination, roasting), reduction to crude metal (smelting, Ellingham diagrams), and refining (zone refining, electrolytic refining) to achieve high elemental purity.",
            "keywords": ["Froth Floatation", "Calcination Roasting", "Ellingham Diagram", "Leaching Process", "Zone Refining"]
        },
        "p-Block Elements": {
            "definition": "Elements belonging to groups 13 to 18 of the periodic table, where the outermost p-subshell is progressively filled with electrons.",
            "explanation": "This block exhibits diverse oxidation states, anomalous behavior of first elements due to small size, and inert pair effects. Key structures include nitrogen compounds (ammonia via Haber's process), oxygen variants, halogens, and noble gases with unique electron configurations.",
            "keywords": ["Inert Pair Effect", "Habers Process", "Allotropes", "Oxidation States", "Interhalogen Compounds"]
        },
        "d and f Block Elements": {
            "definition": "The d-block (transition elements) and f-block (inner transition elements/lanthanides and actinides) contain atoms with partially filled d or f subshells.",
            "explanation": "Transition metals display variable oxidation states, catalytic properties, and colored ion formations due to d-d electron transitions. Lanthanide contraction refers to the steady decrease in atomic and ionic radii with increasing atomic number, impacting chemical reactivity.",
            "keywords": ["Transition Elements", "Lanthanide Contraction", "Variable Valency", "Coordination Complexes", "Actinides"]
        },
        "Coordination Compounds": {
            "definition": "Coordination Compounds consist of a central metal atom or ion bonded to surrounding molecules or ions called ligands via coordinate covalent bonds.",
            "explanation": "Werner's coordination theory explains primary (ionizable) and secondary (non-ionizable) valencies. Valence Bond Theory (VBT) and Crystal Field Theory (CFT) describe d-orbital splitting, magnetic properties, hybridization, and intense geometric stereoisomerism color changes.",
            "keywords": ["Ligands Matrix", "Crystal Field Splitting", "Coordination Number", "Isomerism", "Chelate Effect"]
        },
        "Haloalkanes and Haloarenes": {
            "definition": "Organic compounds derived from alkanes or arenes by replacing one or more hydrogen atoms with halogen atoms.",
            "explanation": "Chemical reactivity is driven by the polar nature of the Carbon-Halogen bond. Aliphatic haloalkanes undergo nucleophilic substitution reactions classified into $S_N1$ (two-step, carbocation intermediate) and $S_N2$ (one-step, bimolecular transition state) pathways, showing stereochemical changes.",
            "keywords": ["Nucleophilic Substitution", "SN1 SN2 Mechanisms", "Chirality", "Electrophilic Substitution", "Grignard Reagent"]
        },
        "Alcohols Phenols and Ethers": {
            "definition": "Organic molecules characterized by functional groups containing oxygen: hydroxyl groups bound to aliphatic carbon (alcohols), aromatic rings (phenols), or oxygen bridging two alkyl groups (ethers).",
            "explanation": "Alcohols show acidic nature determined by inductive effects, synthesized via hydration or reduction. Phenols are significantly more acidic than alcohols due to resonance stabilization of the phenoxide ion. Ethers are relatively unreactive solvents prepared via Williamson's synthesis.",
            "keywords": ["Hydroxyl Group", "Phenoxide Resonance", "Williamsons Synthesis", "Dehydration Reaction", "LucasList"]
        },
        "Aldehydes Ketones and Carboxylic Acids": {
            "definition": "Organic compounds containing the carbonyl group ($C=O$), grouped as aldehydes, ketones, or extended carboxyl groups ($-COOH$).",
            "explanation": "Carbonyl carbons are highly electrophilic, undergoing nucleophilic addition reactions (e.g., aldol condensation, Cannizzaro reaction). Carboxylic acids exhibit higher boiling points and marked acidity due to extensive intermolecular hydrogen bonding and carboxylate ion resonance.",
            "keywords": ["Carbonyl Group", "Aldol Condensation", "Cannizzaro Reaction", "Nucleophilic Addition", "Carboxylate Stabilization"]
        },
        "Amines": {
            "definition": "Amines are nitrogen-containing organic compounds derived by replacing one or more hydrogen atoms of ammonia with alkyl or aryl groups.",
            "explanation": "Amines are classified as primary, secondary, or tertiary, showing basic character due to the lone pair of electrons on nitrogen. Aromatic diazonium salts serve as versatile synthetic intermediates for preparing diverse substituted benzene derivatives via coupling reactions.",
            "keywords": ["Basic Strength", "Hoffmann Bromamide", "Diazonium Salts", "Carbylamine Reaction", "Hinsberg Reagent"]
        },
        "Biomolecules": {
            "definition": "Biomolecules are organic molecules synthesized by living organisms, acting as the structural and functional building blocks of life systems.",
            "explanation": "Carbohydrates (monosaccharides like glucose) provide immediate energy. Proteins are polymers of amino acids linked by peptide bonds, displaying complex folded folding architectures. Nucleic acids (DNA and RNA) serve as genetic blueprints built from nucleotide monomers.",
            "keywords": ["Peptide Bonds", "Carbohydrates", "Amino Acids", "Nucleic Acids", "Denaturation"]
        },
        "Polymers": {
            "definition": "Polymers are high molecular mass macromolecules formed by linking repeating structural monomer units through covalent chemical bonds.",
            "explanation": "Classification includes addition polymers (formed by alkene repeat additions like polythene) and condensation polymers (formed by elimination of small molecules like nylon or bakelite). Biodegradable polymers help mitigate environmental accumulation concerns.",
            "keywords": ["Monomer Units", "Addition Polymerization", "Condensation Elastomers", "Thermoplastics", "Vulcanization"]
        },
        "Chemistry in Everyday Life": {
            "definition": "This chapter examines the practical application of chemical principles in medicine, food production, and cleaning industries.",
            "explanation": "Drugs interact with macromolecular targets classified as analgesics, antibiotics, or antiseptics. Food additives include artificial sweeteners and preservatives. Cleansing agents are split into soaps (sodium salts of fatty acids) and synthetic detergents that clean effectively even in hard water.",
            "keywords": ["Analgesics", "Antibiotics", "Saponification", "Synthetic Detergents", "Preservatives"]
        }
    },
    "Biology": {
        "Reproduction": {
            "definition": "Reproduction is the biological process by which organisms produce offspring similar to themselves, ensuring continuity of species.",
            "explanation": "Asexual reproduction involves a single parent producing genetically identical clones (binary fission, budding). Sexual reproduction involves gamete fusion, generating genetic variation through meiosis and crossing over, which drives evolutionary adaptation.",
            "keywords": ["Binary Fission", "Gamete Fusion", "Meiosis Variation", "Clone Production", "Vegetative Propagation"]
        },
        "Sexual Reproduction in Flowering Plants": {
            "definition": "The specific reproductive mechanism in Angiosperms involving flower structures, microsporogenesis, megasporogenesis, and double fertilization.",
            "explanation": "The stamen generates pollen (male), and the pistil houses the embryo sac (female). Pollination transfers pollen. Double fertilization occurs when one sperm fuses with the egg (syngamy) and another fuses with polar nuclei to form the triploid endosperm for nourishment.",
            "keywords": ["Double Fertilization", "Endosperm", "Pollen Tube", "Megasporogenesis", "Apomixis"]
        },
        "Human Reproduction": {
            "definition": "The physiological processes governing male and female reproductive systems, gametogenesis, fertilization, and embryonic development.",
            "explanation": "Spermatogenesis and oogenesis produce haploid gametes regulated by hormones (LH, FSH). The menstrual cycle prepares the uterine wall monthly. Fertilization in the fallopian tube leads to blastocyst implantation, gestation, and parturition.",
            "keywords": ["Spermatogenesis", "Oogenesis", "Menstrual Cycle", "Blastocyst Implantation", "Placental Hormones"]
        },
        "Reproductive Health": {
            "definition": "A state of complete physical, mental, and social well-being in all matters relating to the reproductive system and its functions.",
            "explanation": "This involves family planning strategies, contraceptive methods (barrier, hormonal, IUDs, sterilization), checking Sexually Transmitted Infections (STIs), and applying Assisted Reproductive Technologies (ART) like IVF to resolve infertility issues.",
            "keywords": ["Contraception", "Amniocentesis", "In Vitro Fertilization", "STIs Prevention", "Infertility Solutions"]
        },
        "Genetics and Evolution": {
            "definition": "Genetics studies heredity and variation, while Evolution examines the processes driving long-term change and diversification in living populations.",
            "explanation": "Mendelian inheritance principles detail dominance, segregation, and independent assortment. Deviations include incomplete dominance and codominance. Evolutionary mechanisms are driven by natural selection, genetic drift, mutations, and isolation factors.",
            "keywords": ["Mendelian Laws", "Alleles", "Natural Selection", "Genetic Drift", "Homologous Organs"]
        },
        "Molecular Basis of Inheritance": {
            "definition": "This topic explores the biochemical structures that encode genetic information, detailing DNA replication, transcription, and translation.",
            "explanation": "DNA acts as the primary genetic material, structured as a double helix. The Central Dogma states information flows from DNA to RNA via transcription, and RNA to Protein via translation. Gene expression regulation is modeled by systems like the Lac Operon.",
            "keywords": ["Double Helix", "Transcription Factor", "Translation Ribosome", "Lac Operon", "DNA Replication"]
        },
        "Biology and Human Welfare": {
            "definition": "The application of biological concepts, disease management, and agricultural enhancements to improve human living conditions.",
            "explanation": "This includes tracking pathogenic immunity, optimizing cattle and crop breeding via tissue culture, and processing organic waste material systems to elevate societal health metrics.",
            "keywords": ["Pathogen Control", "Tissue Culture", "Animal Husbandry", "Biocontrol Agents", "Single Cell Protein"]
        },
        "Human Health and Disease": {
            "definition": "Health is a state of complete physical, mental, and social well-being. Diseases are structural or functional disorders in an organism.",
            "explanation": "Infectious diseases are caused by pathogens (bacteria, viruses, malaria parasites). The body defends itself using innate and acquired immunity (T-cells, B-cells, antibodies). Malfunctions can lead to autoimmune disorders, allergies, or unregulated cancerous cell division.",
            "keywords": ["Innate Acquired Immunity", "Antibodies", "Pathogenic Microbes", "Autoimmunity", "Carcinogens"]
        },
        "Microbes in Human Welfare": {
            "definition": "The domestic, industrial, and environmental applications of microscopic organisms to produce valuable products and treat waste.",
            "explanation": "Microbes drive household fermentation (curd, bread) and industrial production of antibiotics and enzymes. In sewage treatment, aerobic and anaerobic microbes break down organic matter, while methanogens generate biogas from organic waste.",
            "keywords": ["Fermentation", "Sewage Treatment", "Biogas Methanogens", "Penicillin", "Biofertilizers"]
        },
        "Biotechnology Principles and Processes": {
            "definition": "Biotechnology alters living organisms to develop useful products, driven by recombinant DNA technology.",
            "explanation": "The workflow relies on restriction enzymes to cut DNA, cloning vectors to transport target segments, and polymerase chain reactions (PCR) for amplification. Host organisms then express the recombinant proteins in large-scale bioreactors.",
            "keywords": ["Restriction Enzymes", "Cloning Vectors", "PCR Amplification", "Recombinant DNA", "Bioreactors"]
        },
        "Biotechnology and its Applications": {
            "definition": "The practical utilization of biotechnological tools across healthcare, agriculture, and industrial manufacturing.",
            "explanation": "In agriculture, genetic modification creates pest-resistant crops (like Bt Cotton) to reduce chemical use. In medicine, it enables mass production of recombinant insulin, gene therapy interventions for genetic defects, and early molecular diagnostics.",
            "keywords": ["Bt Cotton", "Genetically Modified", "Insulin Production", "Gene Therapy", "Molecular Diagnostics"]
        },
        "Ecology and Environment": {
            "definition": "Ecology is the scientific study of interactions between organisms and their physical environment.",
            "explanation": "Organisms adapt physiologically and behaviorally to abiotic factors (temperature, water, light). Ecosystems cycle nutrients and channel energy flow through trophic food webs, maintaining ecological balance.",
            "keywords": ["Abiotic Factors", "Trophic Levels", "Energy Flow", "Nutrient Cycling", "Homeostasis"]
        },
        "Biodiversity and Conservation": {
            "definition": "The study of the variety of life forms on Earth and the strategic management plans designed to prevent species extinction.",
            "explanation": "Biodiversity faces threats from habitat fragmentation, over-exploitation, and invasive species. Conservation strategies are divided into In-situ (protecting ecosystems naturally in national parks) and Ex-situ (managing species externally in botanical gardens or seed banks).",
            "keywords": ["Biodiversity Loss", "In Situ National Parks", "Ex Situ Seed Banks", "Endemic Species", "Hotspots"]
        }
    },
    "Science": {
        "Chemical Reactions and Equations": {
            "definition": "A process where reactants undergo chemical transformations to form products with entirely different chemical properties, represented using balanced chemical equations.",
            "explanation": "Equations must balance to satisfy the Law of Conservation of Mass. Reactions are classified into combination, decomposition (thermal, electrolytic, photolytic), single displacement, double displacement (precipitation), and oxidation-reduction (redox) processes.",
            "keywords": ["Balanced Equations", "Decomposition", "Displacement", "Redox Reactions", "Exothermic Endothermic"]
        },
        "Acids Bases and Salts": {
            "definition": "Acids produce hydrogen ions ($H^+$) in aqueous solution, bases produce hydroxyl ions ($OH^-$), and salts are ionic compounds formed by their neutralization reaction.",
            "explanation": "Acid-base strength is measured on the logarithmic pH scale, ranging from 0 (highly acidic) to 14 (highly basic). Neutralization generates a salt and water. Industrially important salts include bleaching powder, baking soda, washing soda, and Plaster of Paris.",
            "keywords": ["pH Scale", "Neutralization", "Indicators", "Baking Soda", "Plaster of Paris"]
        },
        "Metals and Non-metals": {
            "definition": "Elements categorized by physical and chemical properties: metals are electropositive and malleable, while non-metals are electronegative and brittle.",
            "explanation": "Metals react with oxygen to form basic oxides and release hydrogen gas from dilute acids, arranged by reactivity in an activity series. Ionic compounds form via electron transfer, displaying high melting points. Metallurgy covers metal extraction from ores.",
            "keywords": ["Reactivity Series", "Ionic Bonding", "Metallurgy Extraction", "Anodizing Corrosion", "Alloys"]
        },
        "Carbon and its Compounds": {
            "definition": "The study of carbon-based molecules, driven by carbon's unique ability to form stable covalent structures.",
            "explanation": "Carbon forms diverse compounds through tetravalency and catenation (self-linking). Hydrocarbons are divided into saturated (alkanes) and unsaturated (alkenes, alkynes). Functional groups dictate chemical behaviors like combustion, oxidation, substitution, and saponification.",
            "keywords": ["Catenation", "Tetravalency", "Homologous Series", "Functional Groups", "Saponification"]
        },
        "Periodic Classification of Elements": {
            "definition": "The historical and modern systematic arrangements used to group chemical elements based on recurring periodic trends in properties.",
            "explanation": "Early frameworks like Mendeleev's periodic law sorted elements by atomic mass. The Modern Periodic Law arranges elements by increasing atomic number ($Z$). Periodic trends show predictable changes in valency, atomic radius, metallic character, and electronegativity across groups and periods.",
            "keywords": ["Modern Periodic Law", "Atomic Number", "Valency Trends", "Atomic Radius", "Electronegativity"]
        },
        "Life Processes": {
            "definition": "The fundamental basic functions performed by living organisms to maintain life, maintain cellular structures, and sustain survival.",
            "explanation": "Key processes include Nutrition (autotrophic photosynthesis vs heterotrophic digestion), Respiration (aerobic vs anaerobic ATP release), Transportation (circulatory pumping systems), and Excretion (filtering metabolic wastes via nephrons).",
            "keywords": ["Photosynthesis", "Aerobic Respiration", "Double Circulation", "Nephron Filtration", "Alveoli Exchange"]
        },
        "Control and Coordination": {
            "definition": "The systemic mechanisms that regulate an organism's internal responses to external environmental stimuli.",
            "explanation": "In animals, coordination relies on the nervous system (neurons, reflex arcs, brain regions) and endocrine hormones (insulin, adrenaline). In plants, control is chemical, driven by tropisms (phototropism, geotropism) and plant hormones like auxins and gibberellins.",
            "keywords": ["Synapse Transmission", "Reflex Arc", "Brain Hemispheres", "Plant Auxins", "Endocrine Hormones"]
        },
        "How do Organisms Reproduce": {
            "definition": "The biological mechanisms organisms use to produce new individuals, maintaining population continuity.",
            "explanation": "Asexual methods include fission, fragmentation, regeneration, budding, and vegetative propagation. Sexual reproduction combines genetic material from two parents, occurring via pollination and double fertilization in plants, and internal fertilization in humans.",
            "keywords": ["Vegetative Propagation", "Placenta Function", "Pollination Vectors", "Puberty Changes", "Contraceptive Methods"]
        },
        "Heredity and Evolution": {
            "definition": "Heredity tracks the genetic transmission of traits across generations, while evolution studies how populations adapt over time.",
            "explanation": "Mendel's experiments with pea plants established laws of inheritance, dominance, and segregation. Sex determination in humans is chromosomal ($XX$/$XY$). Evolution is driven by natural selection, genetic drift, and geographic isolation, creating new species.",
            "keywords": ["Mendelian Traits", "Sex Determination", "Natural Selection", "Speciation Factors", "Fossil Records"]
        },
        "Light Reflection and Refraction": {
            "definition": "Reflection is the bouncing back of light rays from a polished surface. Refraction is the bending of light when passing between optical mediums.",
            "explanation": "Spherical mirrors and thin lenses form images modeled by the mirror formula ($1/f = 1/v + 1/u$) and lens formula ($1/f = 1/v - 1/u$). Refraction is governed by Snell's Law and quantified by the medium's refractive index.",
            "keywords": ["Mirror Formula", "Lens Formula", "Snells Law", "Refractive Index", "Magnification Power"]
        },
        "Human Eye and Colourful World": {
            "definition": "The study of the human eye's anatomy, vision accommodation, and atmospheric optical phenomena.",
            "explanation": "The crystalline lens adjusts focus onto the retina. Vision defects include Myopia (nearsightedness, fixed with concave lenses) and Hypermetropy (farsightedness, fixed with convex lenses). Natural phenomena include prism dispersion, atmospheric refraction (twinkling stars), and Rayleigh scattering (blue sky).",
            "keywords": ["Accommodation Power", "Myopia Hypermetropia", "Prism Dispersion", "Atmospheric Refraction", "Rayleigh Scattering"]
        },
        "Electricity": {
            "definition": "The physical phenomena associated with electric currents, potential differences, and electrical circuit components.",
            "explanation": "Electric current ($I = Q/t$) is measured in Amperes. Potential difference ($V = W/Q$) drives current, governed by Ohm's Law ($V = IR$). Resistors can be connected in series ($R_s = \sum R_i$) or parallel ($1/R_p = \sum 1/R_i$). Joule's law quantifies electrical heat generation ($H = I^2Rt$).",
            "keywords": ["Ohms Law", "Resistors Series", "Parallel Resistance", "Joules Heating", "Electric Power"]
        },
        "Magnetism": {
            "definition": "The forces and field patterns generated by magnets, moving electric charges, and current-carrying coils.",
            "explanation": "Magnetic field lines form closed continuous loops outside a magnet. Hans Oersted discovered that current-carrying wires generate magnetic fields. Field shapes vary for straight wires, circular loops, and solenoids. Right-Hand Thumb and Fleming's Left-Hand Rules determine field and force directions.",
            "keywords": ["Solenoid Field", "Magnetic Field Lines", "Flemings Left Rule", "Electromagnetic Force", "Oersteds Experiment"]
        },
        "Sources of Energy": {
            "definition": "The classification of energy resources into renewable and non-renewable options used to generate power.",
            "explanation": "Conventional sources include fossil fuels, hydro power, and wind energy. Non-conventional options include solar cells, tidal power, geothermal energy, and nuclear fission. Selection balances energy yield against environmental impact.",
            "keywords": ["Fossil Fuels", "Solar Photovoltaic", "Nuclear Fission", "Biomass Energy", "Renewable Resources"]
        },
        "Our Environment": {
            "definition": "The study of ecosystems, biotic-abiotic interactions, waste degradation pathways, and human environmental impacts.",
            "explanation": "Ecosystems contain producers, consumers, and decomposers. Energy flows unidirectionally through trophic food chains, decreasing by 90% at each level. Environmental threats include biomagnification of toxins, ozone layer depletion by CFCs, and waste accumulation.",
            "keywords": ["Trophic Food Chains", "Ten Percent Law", "Ozone Depletion", "Biological Magnification", "Biodegradable Waste"]
        },
        "Management of Natural Resources": {
            "definition": "The sustainable planning and conservation measures used to protect natural resources like forests, wildlife, water, and fossil fuels.",
            "explanation": "Resource conservation relies on the 5 R's: Refuse, Reduce, Reuse, Repurpose, and Recycle. Strategies emphasize sustainable forest management, water harvesting systems (such as Khadins or Bawris), and reducing fossil fuel combustion.",
            "keywords": ["Five Rs Principle", "Water Harvesting", "Sustainable Development", "Deforestation Impact", "Carbon Footprint"]
        }
    },
    "Social science": {
        "The Rise of Nationalism in Europe": {
            "definition": "The historical transition in 19th-century Europe from dynastic empires to self-governed nation-states, driven by nationalist ideologies.",
            "explanation": "The shift began with the French Revolution of 1789, spreading ideals of liberty and equality. Key milestones include the Napoleonic Code, liberal revolutions, Frédéric Sorrieu's utopian visions, and the unifications of Italy (led by Garibaldi and Cavour) and Germany (engineered by Otto von Bismarck).",
            "keywords": ["French Revolution", "Napoleonic Code", "Bismarck Unification", "Liberal Nationalism", "Balkan Crisis"]
        },
        "Nationalism in India": {
            "definition": "The growth of collective anti-colonial consciousness in India, leading to organized struggles against British rule.",
            "explanation": "The movement expanded after Mahatma Gandhi returned from South Africa in 1915, introducing Satyagraha. Key campaigns included the Non-Cooperation Movement, Civil Disobedience Movement (the Dandi Salt March), and the Quit India Movement, uniting diverse social groups against colonial administration.",
            "keywords": ["Satyagraha Philosophy", "Non Cooperation", "Civil Disobedience", "Rowlatt Act", "Poona Pact"]
        },
        "Globalisation and the Indian Economy": {
            "definition": "The integration of national markets with the global economy through cross-border trade, capital flows, and foreign investment.",
            "explanation": "This process accelerated after India introduced economic reforms in 1991 (LPG: Liberalization, Privatization, and Globalization). Multinational Corporations (MNCs) drive globalization by spreading production globally, balancing lower manufacturing costs against local competitive pressures.",
            "keywords": ["Foreign Investment", "MNCs Operation", "Liberalization 1991", "World Trade Org", "Special Economic Zones"]
        },
        "Agriculture": {
            "definition": "The primary economic activity focused on cultivating soil, raising livestock, and producing food and raw materials.",
            "explanation": "Farming types include primitive subsistence, intensive subsistence, and commercial plantation farming. Crops are divided into cropping seasons: Kharif (monsoon crops like rice), Rabi (winter crops like wheat), and Zaid (summer crops). Technological reforms include the Green Revolution.",
            "keywords": ["Subsistence Farming", "Kharif Rabi Zaid", "Green Revolution", "Cash Crops", "Institutional Reforms"]
        },
        "Resources and Development": {
            "definition": "Resources are environmentally available materials that are technologically accessible, economically feasible, and culturally acceptable used to satisfy human needs.",
            "explanation": "Resources are classified by origin (biotic/abiotic), exhaustibility (renewable/non-renewable), and ownership. Over-exploitation requires sustainable development frameworks, resource planning, and soil conservation to combat desertification and erosion.",
            "keywords": ["Sustainable Dev", "Resource Planning", "Soil Erosion", "Renewable Classification", "Rio Earth Summit"]
        },
        "Water Resources": {
            "definition": "The study of freshwater distribution, managing scarcity, and conservation strategies across household and agricultural sectors.",
            "explanation": "Scarcity stems from over-exploitation, unequal distribution, and water pollution. Management relies on Multi-Purpose River Projects (dams), balancing irrigation and hydroelectric gains against ecological displacement. Traditional rainwater harvesting provides a sustainable alternative.",
            "keywords": ["Water Scarcity", "Rainwater Harvesting", "Multipurpose Dams", "Aquifer Depletion", "Drip Irrigation"]
        },
        "Manufacturing Industries": {
            "definition": "Secondary economic activities that process raw materials into higher-value finished goods on a large scale.",
            "explanation": "Industries are classified by raw materials (agro-based like cotton vs mineral-based like iron and steel), ownership (public, private, joint), and scale. Industrial placement balances proximity to raw materials, labor, power, and market access.",
            "keywords": ["Agro Based Industries", "Mineral Processing", "Industrial Location", "Gross Domestic Product", "Pollution Abatement"]
        },
        "Minerals and Energy Resources": {
            "definition": "The distribution and extraction of naturally occurring inorganic crystalline substances and energy reserves used for industrial power.",
            "explanation": "Minerals are grouped as metallic (ferrous/non-ferrous) or non-metallic. Energy resources are split into conventional (coal, petroleum, natural gas) and non-conventional (solar, wind, tidal) sources. Strategic conservation is vital to protect exhaustible reserves.",
            "keywords": ["Metallic Minerals", "Conventional Energy", "Non Conventional Power", "Placer Deposits", "Exhaustible Reserves"]
        },
        "Political Parties": {
            "definition": "Voluntary associations of citizens who share similar political ideologies, contesting elections to gain and hold government power.",
            "explanation": "Parties perform key roles: contesting elections, shaping public policy, and forming governments. Systems vary from one-party configurations to multi-party alliances. Challenges include a lack of internal democracy, dynastic succession, and money power.",
            "keywords": ["Electoral Contests", "Multi Party System", "Coalition Politics", "Political Ideology", "Anti Defection Law"]
        },
        "Federalism": {
            "definition": "A system of governance where power is constitutionally divided between a central authority and constituent regional units.",
            "explanation": "Federalism operates through dual administrative tiers, defined jurisdictions, and independent judicial arbitration. Federations form either by separate states joining together ('coming together') or a large state dividing power ('holding together'). Decentralization creates a local third tier.",
            "keywords": ["Jurisdiction Tiers", "Holding Together", "Decentralization 1992", "State Concurrent Lists", "Constitutional Autonomy"]
        },
        "Democracy and Diversity": {
            "definition": "The study of how democratic political systems respond to social differences, cultural diversities, and deep inequalities.",
            "explanation": "Social divisions emerge from linguistic, racial, or religious differences. Democracies accommodate diversity through political dialogue and power-sharing, ensuring minority inclusion and preventing social differences from escalating into civil conflict.",
            "keywords": ["Social Stratification", "Civil Rights", "Minority Inclusion", "Political Accommodation", "Social Cleavages"]
        },
        "Gender Religion and Caste": {
            "definition": "The social divisions and inequalities built around gender roles, religious identities, and caste hierarchies within democratic politics.",
            "explanation": "Gender inequalities manifest through patriarchal structures, addressed politically by women's representation struggles. Religious divisions can escalate into communalism, combated by secular constitutional frameworks. Caste hierarchies impact voting blocks and affirmative action politics.",
            "keywords": ["Patriarchal Structure", "Communal Politics", "Secular State", "Caste Solidarities", "Affirmative Action"]
        },
        "Outcomes of Democracy": {
            "definition": "An analytical framework used to evaluate the political, economic, and social performance of democratic governments.",
            "explanation": "Democracies are assessed on whether they provide accountable, responsive, and legitimate governance. While they may experience slower economic decision-making compared to dictatorships, democracies perform better at protecting civil liberties and resolving internal social conflicts.",
            "keywords": ["Legitimate Governance", "Accountability", "Civil Liberties", "Conflict Resolution", "Economic Inequality"]
        },
        "Money and Credit": {
            "definition": "Money serves as an authorized medium of exchange. Credit refers to agreements where lenders provide capital based on a promise of future repayment.",
            "explanation": "Money eliminates the double coincidence of wants found in barter systems. Credit operates through formal sectors (regulated banks) and informal sectors (moneylenders charging high interest). Central banks regulate formal credit distribution to protect borrowers.",
            "keywords": ["Medium of Exchange", "Double Coincidence", "Formal Credit Sector", "Collateral Security", "Self Help Groups"]
        },
        "Development": {
            "definition": "A comprehensive process aimed at raising living standards, expanding economic capabilities, and improving overall quality of life.",
            "explanation": "Development goals vary among social groups, sometimes leading to conflicting priorities. National progress is measured by indicators like Per Capita Income, Life Expectancy, and Literacy Rates, integrated into the United Nations' Human Development Index (HDI).",
            "keywords": ["Per Capita Income", "Human Development Index", "Sustainable Targets", "Life Expectancy", "Infant Mortality"]
        },
        "Sectors of Indian Economy": {
            "definition": "The classification of economic activities into Primary, Secondary, and Tertiary sectors based on production profiles.",
            "explanation": "The Primary sector extracts natural resources (farming). The Secondary sector processes raw materials (manufacturing). The Tertiary sector provides support services (transport, banking). Overdependence on agriculture can lead to disguised unemployment, which diversification helps address.",
            "keywords": ["Primary Secondary Tertiary", "Gross Domestic Product", "Disguised Unemployment", "Organized Sector", "Employment Guarantee"]
        }
    },
    "English": {
        "Reading Comprehension": {
            "definition": "The cognitive capability to process text, analyze syntactic relationships, interpret meaning, and extract implicit insights from unread passages.",
            "explanation": "Evaluation focuses on vocabulary inference, identifying core themes, distinguishing factual claims from opinions, and analyzing text structures across discursive, literary, or factual passages.",
            "keywords": ["Contextual Inference", "Thematic Extraction", "Skimming Scanning", "Lexical Vocabulary", "Textual Analytics"]
        },
        "Writing Skills": {
            "definition": "The structured mechanical rules used to compose logical, coherent, and grammatically accurate compositions.",
            "explanation": "Writing assesses format adherence, coherent transitions, vocabulary variety, and tone modulation. Compositions include short notifications, formal invitations, and long-form analytical responses.",
            "keywords": ["Structural Coherence", "Format Adherence", "Paragraph Transitions", "Tone Modulation", "Stylistic Accuracy"]
        },
        "Letter Writing": {
            "definition": "A structured format for formal correspondence, used to communicate with business entities, administrative offices, or editors.",
            "explanation": "Formal letters require a specific layout: sender/receiver addresses, date, concise subject line, formal salutation, an introductory-body-concluding text structure, and a polite sign-off. Evaluation looks at clarity and professional phrasing.",
            "keywords": ["Formal Salutation", "Subject Line Conciseness", "Layout Syntax", "Complimentary Close", "Professional Phrasing"]
        },
        "Article Writing": {
            "definition": "A long-form prose composition written for print or digital media, presenting an organized perspective on a specific topic.",
            "explanation": "Articles follow a structured layout: an engaging title, a byline identifying the author, an introduction outlining the issue, body paragraphs analyzing causes and effects, and a concluding paragraph offering solutions.",
            "keywords": ["Expository Title", "Byline Insertion", "Cause Effect Analysis", "Persuasive Rhetoric", "Concluding Solutions"]
        },
        "Story Writing": {
            "definition": "A creative narrative composition built around a central plot, characters, setting, and thematic message.",
            "explanation": "Story writing uses a clear narrative structure: an introduction establishing characters and setting, a rising action leading to a central conflict or climax, a falling action, and a resolution. Phrasing relies on descriptive adjectives and active verbs.",
            "keywords": ["Plot Construction", "Character Development", "Climax Conflict", "Narrative Resolution", "Descriptive Adjectives"]
        },
        "Tenses": {
            "definition": "Grammatical category that uses verb inflections to indicate the time of an action or state of being relative to the moment of speaking.",
            "explanation": "Tenses are divided into Past, Present, and Future, each containing four aspects: Simple (indefinite habit), Continuous (ongoing action), Perfect (completed action), and Perfect Continuous (actions starting in the past and continuing). Proper application ensures chronological clarity.",
            "keywords": ["Verb Inflections", "Chronological Aspect", "Auxiliary Verbs", "Past Perfect Continuity", "Temporal Reference"]
        },
        "Modals": {
            "definition": "Auxiliary verbs used to express the speaker's attitude or indicate modal values like ability, permission, obligation, possibility, or advice.",
            "explanation": "Modals function as helper verbs alongside a principal base verb. Specific values include: 'Can/Could' for ability or permission, 'May/Might' for possibility, 'Must/Have to' for strict obligation, and 'Should/Ought to' for moral advice.",
            "keywords": ["Modal Auxiliaries", "Epistemic Possibility", "Deontic Obligation", "Helper Verbs", "Permissive Function"]
        },
        "Voice": {
            "definition": "The grammatical relationship indicating whether the grammatical subject performs the action of the verb (Active Voice) or receives the action (Passive Voice).",
            "explanation": "Active voice features direct, subject-first sentence structures ($Subject + Verb + Object$). Transforming sentences to passive voice moves the object first, updates the verb to include a form of 'to be' plus the past participle, and places the original agent in a prepositional phrase ($Object + Auxiliary + V3 + by + Subject$).",
            "keywords": ["Active Passive Transformation", "Past Participle V3", "Transitive Verbs", "Agent Prepositional", "Syntactic Shifting"]
        },
        "Reported Speech": {
            "definition": "The grammatical syntax used to convey spoken words without quoting them directly, shifting direct quotes into indirect statements.",
            "explanation": "Converting direct speech to indirect reported speech requires updating pronouns, adjusting temporal deictics (e.g., changing 'tomorrow' to 'the following day'), and backshifting verb tenses when the introductory reporting verb is in the past tense.",
            "keywords": ["Direct Indirect Shifting", "Tense Backshifting", "Pronominal Alternation", "Reporting Verbs", "Deictic Adjustments"]
        },
        "Determiners": {
            "definition": "A class of modifying words that precede nouns to restrict, quantify, or clarify their reference context.",
            "explanation": "Determiners establish noun reference without adding descriptive attributes. Subcategories include articles (definite 'the', indefinite 'a/an'), demonstratives ('this/that'), possessives ('my/your'), and quantifiers ('some', 'many', 'few', 'each').",
            "keywords": ["Definite Indefinite Articles", "Demonstratives", "Quantifiers", "Noun Modifiers", "Distributives"]
        },
        "Literary Devices": {
            "definition": "Structures and techniques employed by authors to enrich meaning, create rhythm, or evoke emotional depth within textual compositions.",
            "explanation": "Common figures of speech include Simile and Metaphor (comparisons), Personification (attributing human qualities to non-human entities), Alliteration (consonant sound repetition), Irony, Oxymoron, and Hyperbole.",
            "keywords": ["Metaphorical Imagery", "Alliteration Rhythm", "Personification", "Hyperbole Emphasis", "Irony Contrast"]
        },
        "Poetry Analysis": {
            "definition": "The structural and thematic critique of verse, evaluating rhyme schemes, stanza layouts, and figurative language.",
            "explanation": "Analysis examines meter, structural layouts (enjambment, caesura), rhyme schemes, and emotional imagery to understand the poet's underlying themes and intentions.",
            "keywords": ["Rhyme Scheme Metrics", "Stanza Formations", "Enjambment Lines", "Figurative Meaning", "Thematic Critique"]
        },
        "Prose Analysis": {
            "definition": "The critical evaluation of narrative fiction or non-fiction texts to examine plot, character perspectives, and authorial style.",
            "explanation": "Analysis evaluates character motivations, setting influences, shifts in point of view, subtexts, and stylistic choices like tone and diction used to develop narrative arguments.",
            "keywords": ["Authorial Perspective", "Diction Analysis", "Narrative Subtext", "Character Dynamics", "Plot Progression"]
        }
    }
}

QUESTION_PATTERNS = [
    "Explain {topic} in detail.",
    "What do you understand by {topic}?",
    "Define {topic} and explain its significance in {subject}.",
    "Can you elaborate on {topic} with examples?",
    "Discuss the concept of {topic} in {subject}.",
    "What are the key principles of {topic}?",
    "Why is {topic} important in {subject}?",
    "Explain the applications of {topic} in real life.",
    "Differentiate {topic} with related concepts in {subject}.",
    "Give a detailed note on {topic}.",
    "What are the advantages and limitations of {topic}?",
    "How does {topic} work in practical scenarios?",
    "Can you justify the importance of {topic} in modern studies?",
    "Explain {topic} with a real-world example.",
    "What are the main components or elements of {topic}?",
    "Describe the process involved in {topic}.",
    "How is {topic} used in industry or technology?",
    "Provide a structured explanation of {topic}.",
    "Explain {topic} step by step."
]